### ISSUE TITLE
Merging extended epuck code to ARGoS

### ISSUE THREAD

**Issue by jharwell** [ilpincy/argos3#161]
Is there a reason that the extended epuck code here: https://github.com/demiurge-project/argos3-epuck has not been merged to ARGoS ? If not, can I open a pull request to merge it, or alternatively make it a git submodule in ARGoS ? I need a robot with a 3d physics model AND a ground sensor, and the extended epuck is the only robot in ARGoS that meets both those requirements.

**Comment by ilpincy** [comment]
The reason is that the model was developed in a project, Demiurge, and the people working on it wanted to have full freedom on how to develop it. ARGoS should in fact come with *no* robots - the plugin system is meant to make it automatic to discover them. If anything, I'd want to remove the robots rather than add them :)

I think it's safe to install ARGoS along with that repo, but the issue remains that every change we make in the ARGoS core will make plugins obsolete. I think they're on top of things in that repository, for the time being.

**Comment by jharwell** [comment]
Ooooooo I see. That makes sense--I will try to use both side by side then.
