### ISSUE TITLE
Compiling the e-puck plugin  for argos3 59

### ISSUE THREAD

**Issue by teksander** [ilpincy/argos3#178]
Hi Carlo,
In the argos e-puck plugin I changed some lines in the file https://github.com/demiurge-project/argos3-epuck/blob/master/src/cmake/ARGoSBuildChecks.cmake, according to what is required in argos59.

Instead of pkg_check_modules, I changed to:

  set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${ARGOS_PREFIX}/share/argos3/cmake)
  include_directories(${CMAKE_SOURCE_DIR} ${ARGOS_INCLUDE_DIRS})
  link_directories(${ARGOS_LIBRARY_DIR})
  link_libraries(${ARGOS_LDFLAGS})

and also replaced this include:

if(ARGOS_BUILD_FOR_SIMULATOR)
include(FindARGoSQTOpenGL)
endif(ARGOS_BUILD_FOR_SIMULATOR)

The plugin works (actuators and sensors), however the E-pucks are not rendered in the GUI. Do you know where else changes might be required?
Cheers

**Comment by ilpincy** [comment]
I'm not sure, but I'll have a look!

**Comment by teksander** [comment]
Thank you !

**Comment by allsey87** [comment]
The problem is probably related to the variable `ARGOS_COMPILE_QTOPENGL`, which is no longer used but is still declared in [config.h](https://github.com/ilpincy/argos3/blob/f2b2d0d7b5dac6500ae34bb69d03f18ae4502257/src/core/config.h.in#L39).

I haven't checked this, but I think the solution will be to update [SimLibrary.cmake](https://github.com/demiurge-project/argos3-epuck/blob/master/src/plugins/robots/e-puck/SimLibrary.cmake#L24) to check against the variable `ARGOS_QTOPENGL_FOUND` instead of `ARGOS_COMPILE_QTOPENGL`.

**Comment by teksander** [comment]
Thank you @allsey87 !

The two changes I mentioned to [ARGoSBuildChecks.cmake](https://github.com/demiurge-project/argos3-epuck/blob/master/src/cmake/ARGoSBuildChecks.cmake) and the 6 changes to [SimLibrary.cmake](https://github.com/demiurge-project/argos3-epuck/blob/master/src/plugins/robots/e-puck/SimLibrary.cmake#L24) fixed the issue. So far, everything on the e-puck plugin seems to be working in argos59

**Comment by ilpincy** [comment]
Thanks @allsey87! 💯
